name: wakeup_app
description: A new Flutter project for WakeUp app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Localizations
  flutter_localizations:
    sdk: flutter

  # Persistência do cronômetro (FUNDAMENTAL)
  shared_preferences: ^2.2.2

  # Seu banco de dados local (caso use)
  sqflite: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.5

  # Drift (ORM)
  drift: ^2.29.0
  drift_flutter: ^0.2.7

  cupertino_icons: ^1.0.2
  http: ^1.6.0

dev_dependencies:
  drift_dev: ^2.29.0
  build_runner: ^2.10.4

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Fonts (descomente quando adicionar os arquivos)
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Inter-Light.ttf
  #         weight: 300
